const translations = {
  "pl": {
    "tab_start": "Start",
    "tab_planety": "Planety",
    "tab_punkty": "Punkty",
    "tab_detale": "Detale",
    "start_noPlanets": "Stwórz nową planetę lub importuj dane JSON",
    "start_addPoint": "Dodaj punkt",
    "start_label_x": "X (−90 do 90)",
    "start_label_y": "Y (−180 do 180)",
    "start_label_pointName": "Nazwa punktu",
    "start_label_type": "Typ",
    "type_resource": "Zasób",
    "type_base": "Baza",
    "type_ruins": "Ruiny",
    "type_structure": "Struktura",
    "type_other": "Inne",
    "start_label_notes": "Notatki",
    "start_btn_addPoint": "Dodaj punkt",
    "start_scaling": "Skalowanie globu i punktów",
    "start_pointScale": "Skalowanie punktów",
    "start_pointsDistanceMultiplier": "Wysokość słupka",
    "start_globeZoom": "Zoom globu",
    "start_btn_reset": "Reset",
    "start_autoRotate": "Obracanie globu",
    "start_importExport": "Import/Eksport",
    "start_btn_export": "Eksport JSON",
    "start_languageSelector": "Wybierz język",

 "planet_search_placeholder": "Nazwa planety...",
  "planet_filter_biome": "Biom",
  "planet_filter_biomeAlias": "Alias biomu",
  "planet_filter_resource": "Pierwiastki",
  "planet_filter_allResources": "Wszystkie pierwiastki",

  "planet_btn_search": "Szukaj",
  "planet_new_name": "Nazwa nowej planety",
  "planet_btn_create": "Stwórz nową planetę",
  "planet_label_isMoon": "Twórz jako księżyc",
  "planet_btn_generateName": "Generuj nazwę",
  "planet_label_color": "Wybierz kolor",
  "planet_texture_url": "URL tekstury",
  "planet_btn_setTexture": "Ustaw teksturę",
  "planet_btn_setColor": "Zmień kolor",

  "planet_btn_rename": "Zmień nazwę",
  "planet_btn_delete": "Usuń planetę",
  "planet_edit_name": "Nowa nazwa planety",
  "planet_btn_accept": "Akceptuj",
  "planet_btn_cancel": "Anuluj",

  "res_copper": "Miedź",
  "res_cadmium": "Kadm",
  "res_emeril": "Emeril",
  "res_indium": "Ind",
  "res_quartz": "Kwarcyt",
  "res_chromatic_metal": "Metal chromatyczny",
  "res_paraffinium": "Parafin",
  "res_pyrite": "Piryt",
  "res_ammonia": "Amoniak",
  "res_uranium": "Uran",
  "res_dioxite": "Dioksyt",
  "res_phosphorus": "Fosfor",
  "res_basalt": "Bazalt",
  "res_crystal_helium": "Skrystalizowany hel",
  "res_lithium": "Lit",
  "res_cobalt": "Kobalt",
  "res_silver": "Srebro",
  "res_gold": "Złoto",
  "res_magnetised_ferrite": "Namagnesowany ferryt",
  "res_sodium": "Sód",
  "res_salt": "Sól",
  "res_rusty_metal": "Zardzewiały metal",

"points_filter_label": "Filtruj",
  "points_filter_resource": "Zasób",
  "points_filter_base": "Baza",
  "points_filter_ruins": "Ruiny",
  "points_filter_structure": "Struktura",
  "points_filter_other": "Inne",
  "points_filter_poles": "Bieguny",
  "points_filter_myloc": "Moja lokalizacja",
  "points_extra_filters_label": "Filtry dodatkowe",
  "points_extra_mined": "Wydobyty",
  "points_extra_visited": "Odwiedzony",
  "points_extra_unmined": "Niewydobyty",
  "points_extra_unvisited": "Nieodwiedzony",
  "points_sort_label": "Sortuj",
  "sort_name_asc": "Nazwa A–Z",
  "sort_name_desc": "Nazwa Z–A",
  "sort_type": "Typ",
  "sort_newest": "Najnowsze",
  "sort_oldest": "Najstarsze",

  "detail_galaxy_label": "Galaktyka",
  "detail_galaxy_placeholder": "Wybierz galaktykę...",
  "detail_star_system_label": "Układ gwiezdy",
  "detail_planet_system_label": "Układ planetarny",
  "detail_biome_label": "Biom",
  "detail_biome_none": "-- Wybierz biom --",
  "biome_lush": "Bujny",
  "biome_barren": "Jałowy",
  "biome_dead": "Martwy",
  "biome_exotic": "Egzotyczny",
  "biome_mega_exotic": "Mega Egzotyczny",
  "biome_hot": "Spalony",
  "biome_frozen": "Zamrożony",
  "biome_toxic": "Toksyczny",
  "biome_radioactive": "Napromieniowany",
  "biome_swamp": "Bagno",
  "biome_volcanic": "Wulkaniczny",
  "biome_gas_giant": "Gazowy Gigant",

  "detail_biome_alias_label": "Alternatywna nazwa biomu",
  "detail_biome_alias_none": "-- Wybierz alternatywną nazwę --",
  "detail_weather_label": "Pogoda",
  "weather_none": "-- wybierz --",
  "weather_none_atmosphere": "Brak atmosfery",
  "weather_sunny": "Słonecznie",
  "weather_cool": "Chłodno",
  "weather_frosty": "Mroźno",
  "weather_warm": "Ciepło",
  "weather_hot": "Gorąco",
  "weather_humid": "Wilgotno",
  "weather_rainy": "Deszczowo",
  "weather_stormy": "Burzowo",
  "weather_radioactive": "Radioaktywne",
  "weather_toxic": "Toksyczne",
  "weather_acidic": "Kwasyczne",
  "weather_dusty": "Pyłowe",
  "weather_volcanic": "Wulkaniczne",
  "weather_sandstorm": "Burze piaskowe",
  "weather_tornado": "Tornada",
  "weather_meteor": "Meteoryty",
  "weather_firestorm": "Burze ogniste",
  "weather_high_pressure": "Wysokie ciśnienie",
  "weather_low_pressure": "Niskie ciśnienie",
  "weather_magnetic": "Burze magnetyczne",
  "weather_electric": "Burze elektryczne",

  "detail_sentinels_label": "Strażnicy",
  "sentinels_none": "-- wybierz --",
  "sentinels_passive": "Pasywne",
  "sentinels_no": "Brak",
  "sentinels_relaxed": "Zrelaksowane",
  "sentinels_limited": "Ograniczone",
  "sentinels_low": "Niskie",
  "sentinels_low_security": "Niskie bezpieczeństwo",
  "sentinels_minimal": "Minimalne",
  "sentinels_active": "Aktywne",
  "sentinels_medium": "Średnie",
  "sentinels_standard": "Standardowe",
  "sentinels_typical": "Typowe",
  "sentinels_alert": "Uważne",

  "detail_flora_label": "Flora",
  "flora_none": "-- wybierz --",
  "flora_none2": "Brak",
  "flora_sparse": "Sporadyczna",
  "flora_low": "Skąpa",
  "flora_medium": "Średnia",
  "flora_rich": "Obfita",
  "flora_extreme": "Ekstremalna",

  "detail_fauna_label": "Fauna",
  "fauna_none": "-- wybierz --",
  "fauna_none2": "Brak",
  "fauna_sparse": "Sporadyczna",
  "fauna_low": "Skąpa",
  "fauna_medium": "Średnia",
  "fauna_rich": "Obfita",
  "fauna_extreme": "Ekstremalna",

  "detail_discovered_label": "Odkryty przez",
  "detail_mode_label": "Tryb gry",
  "mode_none": "-- wybierz --",
  "mode_normal": "Normalny",
  "mode_creative": "Kreatywny",
  "mode_survival": "Survival",
  "mode_permadeath": "Permadeath",
  "detail_updated_label": "Zaktualizowano",
  "detail_coords_label": "Koordynaty",
  "detail_portal_btn": "Przejdź do NMS Portals",
  "detail_notes_label": "Notatki",
  "detail_save_btn": "Zapisz detale",

planet_noSelected: "Brak wybranej planety",
    alert_enterPlanetSystem: "Wprowadź nazwę układu planetarnego aby poprawnie wyświetlić planetę na liście!",
    alert_savedPlanetDetails: "Opis zapisany!",
    unknown_starSystem: "Nieznany układ gwiezdny",
    unknown_planetSystem: "Nieznany układ planetarny",

  },
  "en": {
    "tab_start": "Start",
    "tab_planety": "Planets",
    "tab_punkty": "Points",
    "tab_detale": "Details",
    "start_noPlanets": "Create a new planet or import JSON data",
    "start_addPoint": "Add point",
    "start_label_x": "X (−90 to 90)",
    "start_label_y": "Y (−180 to 180)",
    "start_label_pointName": "Point name",
    "start_label_type": "Type",
    "type_resource": "Resource",
    "type_base": "Base",
    "type_ruins": "Ruins",
    "type_structure": "Structure",
    "type_other": "Other",
    "start_label_notes": "Notes",
    "start_btn_addPoint": "Add point",
    "start_scaling": "Globe and points scaling",
    "start_pointScale": "Point scale",
    "start_pointsDistanceMultiplier": "Bar height",
    "start_globeZoom": "Globe zoom",
    "start_btn_reset": "Reset",
    "start_autoRotate": "Globe auto-rotate",
    "start_importExport": "Import/Export",
    "start_btn_export": "Export JSON",
    "start_languageSelector": "Select language",

"planet_search_placeholder": "Planet name...",
    "planet_filter_biome": "Biome",
    "planet_filter_biomeAlias": "Biome alias",
    "planet_filter_resource": "Elements",
    "planet_filter_allResources": "All elements",

    "planet_btn_search": "Search",
    "planet_new_name": "New planet name",
    "planet_btn_create": "Create new planet",
    "planet_label_isMoon": "Create as moon",
    "planet_btn_generateName": "Generate name",
    "planet_label_color": "Choose color",
    "planet_texture_url": "Texture URL",
    "planet_btn_setTexture": "Set texture",
    "planet_btn_setColor": "Change color",

    "planet_btn_rename": "Rename",
    "planet_btn_delete": "Delete planet",
    "planet_edit_name": "New planet name",
    "planet_btn_accept": "Accept",
    "planet_btn_cancel": "Cancel",

    "res_copper": "Copper",
    "res_cadmium": "Cadmium",
    "res_emeril": "Emeril",
    "res_indium": "Indium",
    "res_quartz": "Quartz",
    "res_chromatic_metal": "Chromatic Metal",
    "res_paraffinium": "Paraffinium",
    "res_pyrite": "Pyrite",
    "res_ammonia": "Ammonia",
    "res_uranium": "Uranium",
    "res_dioxite": "Dioxite",
    "res_phosphorus": "Phosphorus",
    "res_basalt": "Basalt",
    "res_crystal_helium": "Crystallised Helium",
    "res_lithium": "Lithium",
    "res_cobalt": "Cobalt",
    "res_silver": "Silver",
    "res_gold": "Gold",
    "res_magnetised_ferrite": "Magnetised Ferrite",
    "res_sodium": "Sodium",
    "res_salt": "Salt",
    "res_rusty_metal": "Rusty Metal",

"points_filter_label": "Filter",
  "points_filter_resource": "Resource",
  "points_filter_base": "Base",
  "points_filter_ruins": "Ruins",
  "points_filter_structure": "Structure",
  "points_filter_other": "Other",
  "points_filter_poles": "Poles",
  "points_filter_myloc": "My Location",
  "points_extra_filters_label": "Additional Filters",
  "points_extra_mined": "Mined",
  "points_extra_visited": "Visited",
  "points_extra_unmined": "Unmined",
  "points_extra_unvisited": "Unvisited",
  "points_sort_label": "Sort",
  "sort_name_asc": "Name A–Z",
  "sort_name_desc": "Name Z–A",
  "sort_type": "Type",
  "sort_newest": "Newest",
  "sort_oldest": "Oldest",

  "detail_galaxy_label": "Galaxy",
  "detail_galaxy_placeholder": "Select galaxy...",
  "detail_star_system_label": "Star System",
  "detail_planet_system_label": "Planetary System",
  "detail_biome_label": "Biome",
  "detail_biome_none": "-- Select biome --",
  "biome_lush": "Lush",
  "biome_barren": "Barren",
  "biome_dead": "Dead",
  "biome_exotic": "Exotic",
  "biome_mega_exotic": "Mega Exotic",
  "biome_hot": "Scorched",
  "biome_frozen": "Frozen",
  "biome_toxic": "Toxic",
  "biome_radioactive": "Radioactive",
  "biome_swamp": "Swamp",
  "biome_volcanic": "Volcanic",
  "biome_gas_giant": "Gas Giant",

  "detail_biome_alias_label": "Biome Alternate Name",
  "detail_biome_alias_none": "-- Select alternate name --",
  "detail_weather_label": "Weather",
  "weather_none": "-- select --",
  "weather_none_atmosphere": "No atmosphere",
  "weather_sunny": "Sunny",
  "weather_cool": "Cool",
  "weather_frosty": "Frosty",
  "weather_warm": "Warm",
  "weather_hot": "Hot",
  "weather_humid": "Humid",
  "weather_rainy": "Rainy",
  "weather_stormy": "Stormy",
  "weather_radioactive": "Radioactive",
  "weather_toxic": "Toxic",
  "weather_acidic": "Acidic",
  "weather_dusty": "Dusty",
  "weather_volcanic": "Volcanic",
  "weather_sandstorm": "Sandstorms",
  "weather_tornado": "Tornadoes",
  "weather_meteor": "Meteors",
  "weather_firestorm": "Firestorms",
  "weather_high_pressure": "High Pressure",
  "weather_low_pressure": "Low Pressure",
  "weather_magnetic": "Magnetic Storms",
  "weather_electric": "Electrical Storms",

  "detail_sentinels_label": "Sentinels",
  "sentinels_none": "-- select --",
  "sentinels_passive": "Passive",
  "sentinels_no": "None",
  "sentinels_relaxed": "Relaxed",
  "sentinels_limited": "Limited",
  "sentinels_low": "Low",
  "sentinels_low_security": "Low Security",
  "sentinels_minimal": "Minimal",
  "sentinels_active": "Active",
  "sentinels_medium": "Medium",
  "sentinels_standard": "Standard",
  "sentinels_typical": "Typical",
  "sentinels_alert": "Alerted",

  "detail_flora_label": "Flora",
  "flora_none": "-- select --",
  "flora_none2": "None",
  "flora_sparse": "Sparse",
  "flora_low": "Low",
  "flora_medium": "Moderate",
  "flora_rich": "Rich",
  "flora_extreme": "Extreme",

  "detail_fauna_label": "Fauna",
  "fauna_none": "-- select --",
  "fauna_none2": "None",
  "fauna_sparse": "Sparse",
  "fauna_low": "Low",
  "fauna_medium": "Moderate",
  "fauna_rich": "Rich",
  "fauna_extreme": "Extreme",

  "detail_discovered_label": "Discovered by",
  "detail_mode_label": "Game Mode",
  "mode_none": "-- select --",
  "mode_normal": "Normal",
  "mode_creative": "Creative",
  "mode_survival": "Survival",
  "mode_permadeath": "Permadeath",
  "detail_updated_label": "Updated",
  "detail_coords_label": "Coordinates",
  "detail_portal_btn": "Go to NMS Portals",
  "detail_notes_label": "Notes",
  "detail_save_btn": "Save details",

planet_noSelected: "No planet selected",
    alert_enterPlanetSystem: "Enter the planet system name to display the planet correctly in the list!",
    alert_savedPlanetDetails: "Description saved!",
    unknown_starSystem: "Unknown star system",
    unknown_planetSystem: "Unknown planetary system",

  }
};
